name: GitHub Actions Demo
on: 
  push:
    branches:
      - "main"
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Initial Facts
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "Deploying branch ${{ github.ref }} from ${{ runner.os }} "

      - name: Check out repository code
        uses: actions/checkout@v2
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Get npm deps
        run: npm install
      
      - name: Run Build
        run: npm run build

      - name: Deploy build to S3 Bucket
        run: aws s3 sync build s3://$WEBSITE_BUCKET
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          WEBSITE_BUCKET: ${{ secrets.WEBSITE_BUCKET }}

